import rehypeSanitize, { defaultSchema } from "rehype-sanitize";
import rehypeSlug from "rehype-slug";
import rehypeStringify from "rehype-stringify";
import remarkGfm from "remark-gfm";
import remarkParse from "remark-parse";
import remarkRehype from "remark-rehype";
import { remark } from "remark";
import { visit } from "unist-util-visit";

import type { DocHeading, ParseResult } from "./docModel";

function getTextFromNode(node: unknown): string {
  if (!node || typeof node !== "object") return "";

  const candidate = node as { value?: unknown; children?: unknown[] };
  if (typeof candidate.value === "string") return candidate.value;
  if (Array.isArray(candidate.children)) {
    return candidate.children.map(getTextFromNode).join("");
  }
  return "";
}

export async function parseMarkdownToHtml(markdown: string): Promise<ParseResult> {
  const headings: DocHeading[] = [];

  const mdast = remark().use(remarkParse).use(remarkGfm).parse(markdown);

  // Collect headings from MDAST.
  visit(mdast, "heading", (node: unknown) => {
    const headingNode = node as { depth?: number };
    const depth = headingNode.depth as DocHeading["depth"];
    const text = getTextFromNode(node).trim();

    // id will be generated by rehype-slug later; this is a best-effort placeholder.
    const id =
      text
        .toLowerCase()
        .replace(/[^\w\s-]/g, "")
        .trim()
        .replace(/\s+/g, "-") || `heading-${headings.length + 1}`;

    headings.push({ depth, text, id });
  });

  const schema = {
    ...defaultSchema,
    attributes: {
      ...defaultSchema.attributes,
      // Allow class names for code/pre/span so later phases can style tokens safely.
      code: [...(defaultSchema.attributes?.code || []), ["className"]],
      pre: [...(defaultSchema.attributes?.pre || []), ["className"]],
      span: [...(defaultSchema.attributes?.span || []), ["className"]],
    },
  };

  const file = await remark()
    .use(remarkParse)
    .use(remarkGfm)
    .use(remarkRehype)
    .use(rehypeSlug)
    .use(rehypeSanitize, schema as never)
    .use(rehypeStringify)
    .process(markdown);

  return { html: String(file), headings };
}
